# Generated by Django 5.0.4 on 2024-04-13 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nike_name",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="昵称"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="生日"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="male",
                        max_length=6,
                        verbose_name="性别",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="地址"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default="", max_length=11, verbose_name="手机号"
                    ),
                ),
                (
                    "personl_profile",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="个人简介"
                    ),
                ),
                (
                    "personalized_signature",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="个性签名"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="images/highLightTitle.png",
                        upload_to="images/%Y/%m",
                        verbose_name="用户头像",
                    ),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户详细信息",
                "verbose_name_plural": "用户详细信息",
            },
        ),
    ]
